version: '3.9'
services:
  batch:
    env_file: .env
    image: "registry.gitlab.com/trivialsec/batch/${BUILD_ENV}:${IMAGE_TAG:-latest}"
    container_name: batch
    hostname: batch.trivialsec
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        BUILD_ENV: ${BUILD_ENV}
        TRIVIALSEC_PY_LIB_VER: ${TRIVIALSEC_PY_LIB_VER}
        GITLAB_USER: ${GITLAB_USER}
        GITLAB_PASSWORD: ${GITLAB_PAT}
        CRONICLE_VERSION: ${CRONICLE_VERSION}
    environment:
      - TRIVIALSEC_PY_LIB_VER=${TRIVIALSEC_PY_LIB_VER}
      - APP_ENV=${APP_ENV:-Dev}
      - APP_NAME=${APP_NAME}
      - LOG_LEVEL=${LOG_LEVEL}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
    volumes:
      - ./src:/srv/app/src
      - cache:/var/cache/trivialsec
      - cronicle:/opt/cronicle
    ports:
      - "3012:3012"
    networks:
      default:
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 10
      resources:
        limits:
          cpus: '1.00'
          memory: 2GB
        reservations:
          memory: 1GB

networks:
  default:
    external:
      name: trivialsec

volumes:
  cache:
    external: true
    name: batch-cache
  cronicle:
    external: true
    name: cronicle-datadir
